spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dev

mybatis:
  mapper-locations: com/tj/dal/mapper/*.xml
